name: Deploy to Brainpod

on:
  push:
    branches: ["master"]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: brainpod-spoons-deny
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Login to Brainpod registry
        uses: docker/login-action@v3
        with:
          registry: registry.test.brainpod.io
          
          username: ${{ github.actor }}
          password: ${{ secrets.BRAINPOD_API_KEY }}
          

      - name: Build and push
        uses: brainhivenl/steiger-action@v1
        with:
          cmd: build
          args: --repo=registry.test.brainpod.io/spoons-deny
